title: RK "Izhevsk"
author: admin
email: velo@izh.com
description: > # this means to ignore newlines until "twitter_username:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
# social links
title: Рандоннерский клуб "Ижевск"
twitter_username: jekyllrb
github_username:  jekyll
copyright: © 2018 Рандоннерский клуб "Ижевск". Код ACP 511062.
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

header_pages:
 - 01_calend.md
 - 02_stat.md
 - 03_track.md
 - 04_list.md

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%e.%m.%Y"

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
